import time as t

f = open("sample.txt","wt")
f.write("""hello
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!w
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!

world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!orld!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!
world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!world!!!""")


try:
    f = open("sample.txt","rt")
    begin = t.time()
    print(f.read())
except FileNotFoundError:
    print("파일이 없습니다")
finally:
    f.close()
    end = t.time()

print("read all's time :", (end - begin))

print()
print()
print()

try:
    f = open("sample.txt","rt")
    begin = t.time()
    while True:
        text = f.read(10000)
        if len(text) == 0: break
        print(text, end='')
except FileNotFoundError:
    print("파일이 없습니다")
finally:
    f.close()
    end = t.time()

print()
print("read by 10000's time :", (end - begin))

print()
print()
print()

#with 구문 - 예외처리와 자원정리까지 한꺼번에!
with open("sample.txt", "wt") as f:
    f.write("byebye~")
with open("sample.txt") as f:
    print(f.read())

